apiVersion: demo.upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a-cluster1
  labels:
    owner-team: team-a
spec:
  id: team-a-cluster1
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 5
