apiVersion: demo.upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a-cluster2
  labels:
    owner-team: team-a
spec:
  id: team-a-cluster2
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 2
