apiVersion: demo.upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a-cluster3
spec:
  id: team-a-cluster3
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 5
